config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "works#index"
  
  resources :works do
    collection do
      get 'search'
    end
  end

  resources :recommendations do
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '映画' },
    { id: 2, name: '小説' },
    { id: 3, name: '自己啓発本' },
    { id: 4, name: '漫画' },
    { id: 5, name: 'ドラマ' },
    { id: 6, name: 'アニメ' },
    { id: 7, name: 'ミュージカル' },
    { id: 8, name: '舞台' },
    { id: 9, name: 'ライブ' },
    { id: 10, name: '美術館' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :works, :recommendations
  
  end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  has_one_attached :image

  validates :title, :category_id, presence: true
  validates :title, length: { maximum: 20 }
  validates :memo, length: { maximum: 30 }

end

app/models/star.rb
class Star < ActiveHash::Base
  self.data = [
    { id: 1, name: '★' },
    { id: 2, name: '★★' },
    { id: 3, name: '★★★' },
    { id: 4, name: '★★★★' },
    { id: 5, name: '★★★★★' },
  ]

  include ActiveHash::Associations
  has_many :works
  
  end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category, :star

  has_one_attached :image

  validates :title, :day, :category_id, :star_id, presence: true
  validates :title, length: { maximum: 40 }
  validates :memo, length: { maximum: 1000 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def create
    @recommendation =Recommendation.create(recommendation_params)
    redirect_to search_recommendations_path
  end  
  
  def search
    @recommendation = Recommendation.new
    if params[:q]&.dig(:title)
      squished_keywords = params[:q][:title].squish
      params[:q][:title_cont_any] = squished_keywords.split(" ")
    end
    @q = Recommendation.ransack(params[:q])
    @recommendations = @q.result.order("created_at DESC").page(params[:page]).per(6)
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
    redirect_to search_recommendations_path
  end



  private

  def recommendation_params
    params.require(:recommendation).permit(:title, :category_id, :memo, :image)
  end


end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    if params[:q]&.dig(:title)
      squished_keywords = params[:q][:title].squish
      params[:q][:title_cont_any] = squished_keywords.split(" ")
    end
    @q = Work.ransack(params[:q])
    @works = @q.result.order("created_at DESC").page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @work.update(work_params)
      redirect_to work_path(@work.id)
    else
      render :edit
    end
  end

  def destroy
    @work.destroy
    redirect_to search_works_path
  end


  private

  def work_params
    params.require(:work).permit(:title, :category_id, :day, :star_id, :memo, :image)
  end

  def set_work
    @work = Work.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewingDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@300&family=Kiwi+Maru:wght@300&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@300&family=Roboto:wght@100&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recommendations/search.html.erb
<%= render "shared/header" %>
<%# <div class="recommendation-new-post-btn" > %>
<div class="button-content" >
    <label class="btn btn-outline-danger btn-lg" for="new-post">New Post</label>
    <input type="checkbox" id="new-post">
    <label class="btn btn-outline-primary btn-lg" for="search">Search</label>
    <input type="checkbox" id="search">

    <%# おすすめ投稿 %>
    <div id="new-post-content" class="new-recommendation" >
      <%= form_with model: @recommendation,local: true do |f| %>
        <div class="recommendation-items">
          <div class="recommendation-img-upload">
            <div class="weight-bold-text">Image</div>
            <div class="recommendation-click-upload">
              クリックしてアップロード
              <%= f.label :image, "Choose", class: "recommendation-image_input_btn" %>
              <%= f.file_field :image, class:"recommendation-item-image" %>
            </div>
          </div>
          <div class="recommendation-category">
            <div class="weight-bold-text">
              Category
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "Choose"}, {class:"recommendation-select-box", id:"category"}) %>
          </div>
        </div>

        <div class="new-recommendation-text">
          <div class="recommendation-title">
            <div class="weight-bold-text">
              Title
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_area :title, class:"recommendation-items-text", id:"item-name", placeholder:"作品名（必須 40文字まで)", maxlength:"20" %>
          </div>
          <div class="recommendation-items-explain">
            <div class="weight-bold-text">Memo</div>
            <%= f.text_area :memo, class:"recommendation-items-text", id:"item-info", placeholder:"メモ（1,000文字まで）" ,rows:"2" ,maxlength:"30" %>
         </div>
       </div>

       <div class="d-grid gap-2"> 
         <%= f.submit "POST" ,class:"btn btn-danger" %>
       </div>

    </div>
    <% end %>
    <%# /おすすめ投稿 %>

    <%# </div> %>
    <%# <おすすめ検索> %>
    <div id="search-content" class="recommendation-search">
      <%= search_form_for @q, url: search_recommendations_path do |f| %>
        <div class="recommendation-search-category">
          <%= f.label :category_id_in, 'Category', class: "search-size" %>
          <br>
          <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name, {include_blank: "---"}) %>
        </div>
        <div class="recommendation-search-title">
          <div class="recommendation-search-field">
            <%= f.label :title, 'Title', class: "search-size" %>
            <br>
            <%= f.text_field :title, class:"search-title-text", placeholder: 'Title', value: params[:q]&.dig(:title) %>
          </div>
          <div class="search-submit">
            <%= f.submit 'Search', class:"btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    <%# </おすすめ検索> %>
</div>

<%# <一覧表示> %>
<div class="list_wrapper">
  <% @recommendations.each do |recommendation| %>
  <div class="list">
    <div class="list-image-wrapper">
      <% if recommendation.image.present? %>
        <%= image_tag recommendation.image, class:"list_img" %>
      <% else %>
        <%= image_tag 'noimage2.jpg', class:"list_img" %>
      <% end %>
      <div class="list-delete">
        <%= link_to "DELETE",recommendation_path(recommendation.id) , method: :delete, class: "list-delete-btn", data: { confirm: "削除しますか？" } %>
      </div>
    </div>

    <div class="list-text">
      <div>
        <div class="list-weight-bold-content">Title</div>
        <%= recommendation.title %>
      </div>
      <div>
        <div class="list-weight-bold-content">Category</div>
        <%= Category.find(recommendation.category_id).name %>
      </div>
      <div>
        <div class="list-weight-bold-content">Posted Date</div>
        <%= recommendation.created_at.strftime('%Y/%m/%d')%>
      </div>
      <div>
        <div class="list-weight-bold-content">Memo</div>
        <%= recommendation.memo %>
      </div>
    </div>
  </div>
  <% end %>
  <%# </一覧表示> %>
</div>

<%= paginate @recommendations, theme: 'bootstrap-5' %>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- フッター -->
  <footer class="footer">
    <div class="copyright">Copyright©️2022 VIEWING DIARY</div>
  </footer>
</div>

app/views/shared/_header.html.erb
<div class="layout-wrapper">
  <!-- ヘッダー -->
  <header class="header">
      <div class="heading">
        <%= link_to 'VIEWING DIARY', "/", class:"apptitle" %>
      </div>
      <div class="center-block">
          <%= link_to 'LIST VIEW',search_works_path,class:"nav-list" %>
          <%= link_to 'RECOMMENDED',search_recommendations_path,class:"nav-recommended" %>
      </div>
   </header>

app/views/works/edit.html.erb
<div class="layout-wrapper">
  <!-- ヘッダー -->
  <header class="header">
      <div class="new-heading">
        <%= link_to 'VIEWING DIARY', "/", class:"apptitle" %>
      </div>
  </header>

  <div class="new-image-content" >
  <div class="new-main">
    <h2 class="new-title">EDIT</h2>
    <%= form_with model: @work,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        Image
      </div>
      <div class="click-upload">
          クリックしてファイルをアップロード
        <%= f.label :image, "Choose", class: "image_input_btn" %>
        <%= f.file_field :image, class:"item-image" %>
      </div>
    </div>
    <%# /画像 %>
    <%# 作品詳細 %>
    <div class="new-items">
      <div class="form">
        <div class="day">
          <div class="weight-bold-text">
          Day
          <span class="indispensable">必須</span>
          </div>
          <%= f.date_field :day, class: 'date-select' %>
        </div>
        <div>
          <div class="weight-bold-text">
            Category
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "Choose"}, {class:"select-box", id:"category"}) %>
        </div>
        <div>
          <div class="weight-bold-text">
            Star
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:star_id, Star.all, :id, :name, {include_blank: "Choose"}, {class:"select-box", id:"star"}) %> 
        </div>
      </div>
      <div class="weight-bold-text">
        Title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"作品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          Memo
        </div>
        <%= f.text_area :memo, class:"items-text", id:"item-info", placeholder:"感想など（1,000文字まで）" ,rows:"3" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /作品詳細 %>

    <%# 下部ボタン %>
    <div class="d-grid gap-2"> 
      <%= f.submit "EDIT" ,class:"btn btn-danger" %>
    </div>
    <%# /下部ボタン %>
  </div>
    <% end %>
 </div>

  <!-- フッター -->
  <footer class="footer">
    <div class="copyright">Copyright©️2022 VIEWING DIARY</div>
  </footer>
</div>

app/views/works/index.html.erb
<%= render "shared/header" %>

    <!-- トップページのメイン -->
  <div class="index-main">
    <div class="post">
      <%= image_tag"top.JPG", class:"main-image" %>
      <div class="new-post-btn">
        <%= link_to 'NEW POST',new_work_path %>
      </div>
    </div>
  </div>

<%= render "shared/footer" %>

app/views/works/new.html.erb
<div class="layout-wrapper">
  <!-- ヘッダー -->
  <header class="header">
      <div class="new-heading">
        <%= link_to 'VIEWING DIARY', "/", class:"apptitle" %>
      </div>
  </header>

  <div class="new-image-content" >
  <div class="new-main">
    <h2 class="new-title">NEW POST</h2>
    <%= form_with model: @work,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        Image
      </div>
      <div class="click-upload">
          クリックしてファイルをアップロード
        <%= f.label :image, "Choose", class: "image_input_btn" %>
        <%= f.file_field :image, class:"item-image" %>
      </div>
    </div>
    <%# /画像 %>
    <%# 作品詳細 %>
    <div class="new-items">
      <div class="form">
        <div class="day">
          <div class="weight-bold-text">
          Day
          <span class="indispensable">必須</span>
          </div>
          <%= f.date_field :day, class: 'date-select' %>
        </div>
        <div>
          <div class="weight-bold-text">
            Category
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "Choose"}, {class:"select-box", id:"category"}) %>
        </div>
        <div>
          <div class="weight-bold-text">
            Star
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:star_id, Star.all, :id, :name, {include_blank: "Choose"}, {class:"select-box", id:"star"}) %>
        </div>
      </div>
      <div class="weight-bold-text">
        Title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"作品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          Memo
        </div>
        <%= f.text_area :memo, class:"items-text", id:"item-info", placeholder:"感想など（1,000文字まで）" ,rows:"3" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /作品詳細 %>

    <%# 下部ボタン %>
    <div class="d-grid gap-2"> 
      <%= f.submit "POST" ,class:"btn btn-danger" %>
    </div>
    <%# /下部ボタン %>
  </div>
    <% end %>
 </div>

  <!-- フッター -->
  <footer class="footer">
    <div class="copyright">Copyright©️2022 VIEWING DIARY</div>
  </footer>
</div>

app/views/works/search.html.erb
<%= render "shared/header" %>

  <%= search_form_for @q, url: search_works_path do |f| %>
<div class="work-contents">
    <div class="work-contents-search">
      <div class="search-field">
        <%= f.label :title, 'Title', class: "search-size" %>
        <br>
        <%= f.text_field :title, placeholder: 'Title', value: params[:q]&.dig(:title) %>
      </div>
      <div class="search-field">
        <%= f.label :day_gteq, 'Day', class: "search-size"%>
        <br>
        <%= f.date_field :day_gteq %>〜<%= f.date_field :day_lteq %> 
      </div>
      <div class="search-field">
        <%= f.label :star_id_in, 'Star', class: "search-size" %>
        <br>
        <%= f.collection_check_boxes(:star_id_in, Star.all, :id, :name, {include_blank: "---"}) %>
      </div>
    </div>
      <div class="search-field-category">
        <%= f.label :category_id_in, 'Category', class: "search-size" %>
        <br>
        <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name, {include_blank: "---"}) %>
        <%= f.submit 'Search', class:"btn btn-outline-secondary" %>
      </div>
</div>
  <% end %>

<div class="card__wrapper">
  <% @works.each do |work| %>
  <div class="card border-0">
    <div class="image__wrapper" >
    <% if work.image.present? %>
      <%= link_to image_tag(work.image, class: :card__img ), work_path(work.id) %>
    <% else %>
      <%= link_to image_tag('noimage.jpg', class: :card__img ), work_path(work.id) %>
    <% end %>
    </div>
    <div class="card__body">
    <%= link_to work.title, work_path(work.id), class: :card__title%>
    </div>
    <div class="card__summary">
    <%= Category.find(work.category_id).name%>
    </div>
  </div>
  <% end %>
</div>

  <%= paginate @works, theme: 'bootstrap-5' %>

<%= render "shared/footer" %>

app/views/works/show.html.erb
<%= render "shared/header" %>

    <%# /作品詳細 %>
    <div class="show-items">
      <div class="title-name">
        <%= @work.title %>
      <%# /ボタン %>
        <div class="show__manage">
          <%= link_to "EDIT", edit_work_path(@work.id), class: "btn btn-outline-primary" %>
          <%= link_to "DELETE",work_path(@work.id) , method: :delete, class: "btn btn-outline-danger", data: { confirm: "削除しますか？" } %>
        </div>
      <%# /ボタン %>
      </div>
      <div class="show-image">
        <% if @work.image.present? %>
          <%= image_tag @work.image %>
        <% else %>
          <%= image_tag 'noimage.jpg' %>
        <% end %>
      </div>

      <div class="show-content">
        <div>
          <div class="show-weight-bold-content">Day</div>
          <%= @work.day%>
        </div>
        <div>
          <div class="show-weight-bold-content">Category</div>
          <%= Category.find(@work.category_id).name %>
        </div>
        <div>
          <div class="show-weight-bold-content">Star</div>
          <%= Star.find(@work.star_id).name %>
        </div>
      </div>

      <div class="show-under-content">
        <div class="show-weight-bold-content">Memo</div>
        <%= @work.memo %>
      </div>
      <%# /作品詳細 %>


    </div>

<%= render "shared/footer" %>